version: "3.7"

services:
  rng:
    image: cgerull/dckr-training-rng:1.0
    networks:
    - dockercoins
    ports:
    - "8001:80"

  hasher:
    image: cgerull/dckr-training-hasher:1.0
    networks:
    - dockercoins
    ports:
    - "8002:80"

  webui:
    image: cgerull/dckr-training-webui:1.1
    networks:
    - dockercoins
    ports:
    - "8000:80"

  redis:
    image: redis
    networks:
    - dockercoins

  worker:
    image: cgerull/dckr-training-worker:1.0
    networks:
    - dockercoins

networks:
    dockercoins:
