version: "3.7"

services:
  rng:
    build:
      context: ./rng
    image: cgerull/dckr-training-rng:1.1
    networks:
    - dockercoins
    # ports:
    # - "8001:80"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  hasher:
    build:
      context: ./hasher
    image: cgerull/dckr-training-hasher:1.0
    networks:
    - dockercoins
    ports:
    - "8002:80"

  webui:
    build:
      context: ./webui
    image: cgerull/dckr-training-webui:1.1
    networks:
    - dockercoins
    ports:
    - "8000:80"

  redis:
    image: redis
    networks:
    - dockercoins

  worker:
    build:
      context: ./worker
    image: cgerull/dckr-training-worker:1.0
    networks:
    - dockercoins
    deploy:
      replicas: 10
      update_config:
          parallelism: 2
          delay: 10s
      restart_policy:
        condition: on-failure

networks:
    dockercoins:
